# Configuration for Main Database
spring:
  application:
    name: acmebank
  datasource:
    url: jdbc:h2:file:./db/acmebank;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

